name: PlayerDuels
version: 1.0.0
main: siroswaldo.playerduels.PlayerDuels
api-version: 1.13
authors: [SirOswaldo]
description: Reta a otros jugadores a un duelo!
website: https://kayteam.org
commands:
  playerduelsadmin:
    description: admin command!
    permission: playerduels.admin
    aliases:
      - pda
permissions:
  playerduels.admin:
    description: admin permission!