name: PlayerDuels
version: 1.0.0
main: siroswaldo.playerduels.PlayerDuels
api-version: 1.13
authors: [SirOswaldo]
description: Reta a otros jugadores a un duelo!
website: https://kayteam.org
commands:
  playerduelsmanager:
    description: can manage this plugin with this command!
    permission: playerduels.admin
    aliases:
      - playerduelm
      - playerdm
      - pdm
  playerduelsarena:
    description: can manage arenas whit this command!
    permission: playerduels.arena
    aliases:
      - playerduelsa
      - playerda
      - pda
  duelpetition:
    description: can send duels petitions with this command!
    permission: playerduels.duelpetition
    aliases:
      - duelp
      - dpetition
      - dp
  duelaccept:
    description: can accept duels with this command!
    permission: playerduels.duelaccept
    aliases:
      - duela
      - daccept
      - da
  duelreject:
    description: can reject duels witch this command!
    permission: playerduels.duelreject
    aliases:
      - duelr
      - dreject
      - dr
permissions:
  playerduels.manager:
    description: can execute playerduelsadmin command!
  playerduels.arena:
    description: can execute playerduelsarena command!
  playerduels.duelpetition:
    description: can execute duelpetition command!
  playerduels.duelaccept:
    description: can execute duelaccept command!
  playerduels.duelreject:
    description: can execute duelreject command!
    # hacer el apostador
    # crear task de la peticion
    # crear sistema de puntos
    #